#ifndef __BLE_LINK_SESSION_H__
#define __BLE_LINK_SESSION_H__

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "esp_err.h"

#include "ble_link_dispatcher.h"
#include "ble_link_state.h"

#ifdef __cplusplus
extern "C" {
#endif

/** @brief Derived link session states. */
typedef enum
{
    BLE_LINK_SESSION_INACTIVE = 0,    /**< No active ACL. */
    BLE_LINK_SESSION_CONNECTED,       /**< ACL up, admission facts pending. */
    BLE_LINK_SESSION_AUTHENTICATED,   /**< Session channel admitted. */
    BLE_LINK_SESSION_AUTHORIZED,      /**< Control channel admitted. */
} ble_link_session_state_t;

/** @brief Asynchronous connection facts reported to the session. */
typedef enum
{
    BLE_LINK_SESSION_EVENT_ACL_CONNECTED = 0,
    BLE_LINK_SESSION_EVENT_ACL_DISCONNECTED,
    BLE_LINK_SESSION_EVENT_LINK_ENCRYPTED,
    BLE_LINK_SESSION_EVENT_SC_BOND_VERIFIED,
} ble_link_session_event_t;

/**
 * @brief Report a change to the committed authorization record.
 *
 * The authorization record is a persistent device fact with a monotonic
 * revision from the caller. An event whose revision is not newer than the
 * last accepted one is ignored, so late or reordered callbacks cannot
 * resurrect an authorization that was revoked. The record is not tied to
 * any connection generation: it survives disconnects and is reflected in
 * the BOUND state flag.
 *
 * @param[in] committed True when an authorization record is committed.
 * @param[in] revision  Monotonic revision of the authorization change.
 * @return ESP_OK, including stale revisions.
 */
esp_err_t ble_link_session_set_authorization(
    bool committed, uint32_t revision);

/**
 * @brief Report a Security 2 session open or close.
 *
 * Each Security 2 transition carries a strictly increasing epoch from the
 * caller. A transition whose epoch is not newer than the last accepted one
 * is ignored, so a late callback from a closed handshake cannot reopen the
 * session. Every accepted transition, open or close, invalidates the
 * current session match; after an open, the session must match again with
 * the same epoch before control access returns. Closing preserves the ACL
 * and bond facts.
 *
 * @param[in] generation Current connection generation.
 * @param[in] open       True when the Security 2 session opened.
 * @param[in] epoch      Monotonic epoch of this transition.
 * @return ESP_OK (including stale epochs), or ESP_ERR_INVALID_STATE when
 *         the generation is not current.
 */
esp_err_t ble_link_session_security2(
    uint32_t generation, bool open, uint32_t epoch);

/**
 * @brief Report that the current generation session matched the committed
 * authorization record.
 *
 * Called after a Security 2 handshake completes with the long-term
 * credentials whose authorization record was committed at the given
 * revision. The call succeeds only while the Security 2 session opened by
 * the given epoch is still current, a committed record exists, and the
 * revision equals the current record revision; a match for a revoked or
 * replaced record, or for a closed handshake, has no effect.
 *
 * @param[in] generation      Current connection generation.
 * @param[in] revision        Authorization revision the session matched.
 * @param[in] security2_epoch Epoch of the Security 2 session that matched.
 * @return ESP_OK, or ESP_ERR_INVALID_STATE when the epoch is not current,
 *         no committed record matches the revision, or the generation is
 *         not current.
 */
esp_err_t ble_link_session_report_session_match(
    uint32_t generation, uint32_t revision, uint32_t security2_epoch);

/** @brief Characteristics whose admission the session gates. */
typedef enum
{
    BLE_LINK_SESSION_CHANNEL_LINK_STATE = 0,
    BLE_LINK_SESSION_CHANNEL_SESSION,
    BLE_LINK_SESSION_CHANNEL_CONTROL,
    BLE_LINK_SESSION_CHANNEL_EVENT,
} ble_link_session_channel_t;

/**
 * @brief Initialize the session manager for a boot.
 *
 * @param[in] boot_id Fresh nonzero random value for this boot, generated by
 *                    the caller.
 */
void ble_link_session_init(uint64_t boot_id);

/**
 * @brief Reset to an inactive, empty session (new boot or full teardown).
 */
void ble_link_session_reset(void);

/**
 * @brief Report one asynchronous connection fact.
 *
 * Every event is checked against the current generation; late events from a
 * retired generation have no effect and return ESP_OK. ACL connection
 * generations must be strictly increasing: an ACL_CONNECTED with a
 * generation not newer than the last accepted one is ignored (ESP_OK), while
 * a genuinely new connection while a session is active is rejected with
 * ESP_ERR_INVALID_STATE.
 *
 * @param[in] generation Current connection generation.
 * @param[in] event      Reported fact.
 * @return ESP_OK (including ignored stale events), or
 *         ESP_ERR_INVALID_STATE for a fact inconsistent with the current
 *         session state.
 */
esp_err_t ble_link_session_handle_event(
    uint32_t generation, ble_link_session_event_t event);

/**
 * @brief Open or close the local pairing window.
 *
 * An unknown peer may pair only while the window is open.
 *
 * @param[in] open True to open the window.
 */
void ble_link_session_set_pairing_window(bool open);

/**
 * @brief Query admission for one characteristic.
 *
 * @param[in]  generation Current connection generation.
 * @param[in]  channel    Characteristic channel.
 * @param[out] out_error  Stable LinkError value: BLE_LINK_ERROR_OK when
 *                        admitted, or a rejection code.
 * @return ESP_OK, or ESP_ERR_INVALID_ARG.
 */
esp_err_t ble_link_session_query_admission(
    uint32_t generation, ble_link_session_channel_t channel,
    uint32_t *out_error);

/**
 * @brief Current session state for the given generation.
 *
 * @param[in] generation Current connection generation.
 * @return State, or BLE_LINK_SESSION_INACTIVE when no session matches.
 */
ble_link_session_state_t ble_link_session_get_state(uint32_t generation);

/**
 * @brief Session facts for the current connection generation.
 *
 * @param[in]  generation Current connection generation.
 * @param[out] facts      Facts filled with the current admission state.
 * @return ESP_OK when a session is active, ESP_ERR_INVALID_STATE otherwise.
 */
esp_err_t ble_link_session_get_facts(
    uint32_t generation, ble_link_dispatcher_facts_t *facts);

/**
 * @brief Current PublicLinkState flags for the boot.
 *
 * BINDABLE reflects the local pairing window; BOUND reflects the existence
 * of a committed authorization record (a persistent device fact, not tied
 * to the current connection).
 *
 * @return BLE_LINK_STATE_FLAG_BINDABLE and/or BLE_LINK_STATE_FLAG_BOUND.
 */
uint32_t ble_link_session_get_state_flags(void);

#ifdef __cplusplus
}
#endif

#endif /* __BLE_LINK_SESSION_H__ */
