#ifndef __WEATHER_HOST_SDKCONFIG_H__
#define __WEATHER_HOST_SDKCONFIG_H__

#define CONFIG_MAIN_PROJECT_TASK_CORE_ID 0
#define CONFIG_WEATHER_SERVICE_MAX_RESPONSE_BYTES 262144
#define CONFIG_WEATHER_SERVICE_TASK_STACK_SIZE 8192

#endif /* __WEATHER_HOST_SDKCONFIG_H__ */
